"""Package a QLoRA adapter + retrieval index + embedder into a SageMaker `model.tar.gz`.

Tier-14D deliverable. Bundles four things into the SageMaker S3 layout:

    model.tar.gz
      code/
        inference.py          ← publish/sagemaker_handler.py (renamed)
        requirements.txt      ← runtime deps (peft + transformers + bitsandbytes
                                + faiss-cpu + sentence-transformers)
      adapter/                ← QLoRA adapter from tier 12A
      retrieval/
        index.faiss
        gold_pairs.jsonl
      embedder/               ← MPNet snapshot (no internet at endpoint)

The endpoint stand-up script (`scripts/deploy_endpoint.py`, written at
tier 14C) uploads this archive to S3 and creates the SageMaker model +
endpoint config referencing it.

Snapshot strategy for the embedder: we ship the MPNet model files
verbatim in the tar so the endpoint never has to hit huggingface.co
(no outbound internet required). Run `sentence-transformers` once
locally to populate `~/.cache/huggingface/`, then this script copies
the snapshot dir into the archive.

This module is import-safe (no side effects on import). The CLI is at
the bottom — `python -m publish.package_model --help` shows usage.
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
import tarfile
from pathlib import Path

from daccord.validation import ValidatedModel, validated

log = logging.getLogger("package_model")

# Versions pulled into requirements.txt at packaging time. Keep aligned
# with the consumer/ pyproject (same client-side stack).
RUNTIME_REQUIREMENTS = """\
# Generated by publish/package_model.py — do not hand-edit.
# Versions pinned to match the consumer env so endpoint inference
# behaves identically to local-mode demo (consumer/app.py).
torch>=2.7,<3
transformers>=5.9,<6
peft>=0.19,<1
bitsandbytes>=0.49,<1
sentence-transformers>=5.5,<6
faiss-cpu>=1.14,<2
pydantic>=2.13,<3
pyarrow>=23,<24
pillow>=12,<13
"""


class PackageArgs(ValidatedModel):
    """Validated CLI args. Wrapped so the package function gets type-checked input."""

    adapter_path: Path
    retrieval_index_stem: Path  # path without .faiss/.jsonl suffix
    embedder_snapshot: Path
    output_archive: Path
    handler_path: Path = Path(__file__).parent / "sagemaker_handler.py"


@validated
def package(args: PackageArgs) -> Path:
    """Build `model.tar.gz`. Returns the output archive path.

    Validates that every input exists before opening the tarball — fast
    fail beats half-written archive.
    """
    if not args.adapter_path.exists():
        raise FileNotFoundError(f"adapter not found: {args.adapter_path}")
    faiss_file = args.retrieval_index_stem.with_suffix(".faiss")
    jsonl_file = args.retrieval_index_stem.with_suffix(".jsonl")
    for p in (faiss_file, jsonl_file):
        if not p.exists():
            raise FileNotFoundError(f"retrieval index sidecar missing: {p}")
    if not args.embedder_snapshot.exists():
        raise FileNotFoundError(f"embedder snapshot not found: {args.embedder_snapshot}")
    if not args.handler_path.exists():
        raise FileNotFoundError(f"handler not found: {args.handler_path}")

    args.output_archive.parent.mkdir(parents=True, exist_ok=True)
    # Stage to a temp directory so the archive layout is exactly what
    # SageMaker expects — preserves arcname semantics across tarfile + zip
    # consumers.
    staging = args.output_archive.parent / f".staging-{args.output_archive.stem}"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    # code/
    code_dir = staging / "code"
    code_dir.mkdir()
    shutil.copy2(args.handler_path, code_dir / "inference.py")
    (code_dir / "requirements.txt").write_text(RUNTIME_REQUIREMENTS, encoding="utf-8")

    # adapter/
    shutil.copytree(args.adapter_path, staging / "adapter")

    # retrieval/
    retrieval_dir = staging / "retrieval"
    retrieval_dir.mkdir()
    shutil.copy2(faiss_file, retrieval_dir / "index.faiss")
    shutil.copy2(jsonl_file, retrieval_dir / "index.jsonl")

    # embedder/
    shutil.copytree(args.embedder_snapshot, staging / "embedder")

    # Tar the staging dir as gzip
    log.info("staging at %s", staging)
    with tarfile.open(args.output_archive, "w:gz") as tar:
        # arcname="." puts everything at the archive root, matching
        # SageMaker's expectation (no top-level wrapper directory).
        tar.add(staging, arcname=".")

    shutil.rmtree(staging)
    log.info("wrote %s (%.1f MB)", args.output_archive, args.output_archive.stat().st_size / 1e6)
    return args.output_archive


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--adapter-path",
        type=Path,
        required=True,
        help="QLoRA adapter directory from tier 12A (peft.PeftModel.save_pretrained output)",
    )
    parser.add_argument(
        "--retrieval-index-stem",
        type=Path,
        required=True,
        help="retrieval index stem (without .faiss/.jsonl suffix) — built via "
        "envs/eval/scripts/build_retrieval_index.py",
    )
    parser.add_argument(
        "--embedder-snapshot",
        type=Path,
        required=True,
        help="local MPNet snapshot dir (typically ~/.cache/huggingface/.../snapshots/<hash>)",
    )
    parser.add_argument(
        "--output-archive",
        type=Path,
        default=Path("dist/model.tar.gz"),
        help="output archive path (default: dist/model.tar.gz)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    package(
        PackageArgs(
            adapter_path=args.adapter_path,
            retrieval_index_stem=args.retrieval_index_stem,
            embedder_snapshot=args.embedder_snapshot,
            output_archive=args.output_archive,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
